apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: metrics-certs
  namespace: system
spec:
  subject:
    organizations:
    - k8s-sig-node
  dnsNames:
  - nrr-metrics-service.nrr-system.svc
  - nrr-metrics-service.nrr-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: metrics-server-cert
